// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hubs.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHub = `-- name: CreateHub :one
INSERT INTO hubs (tenant_id, name, code, manager_id, address_line1, address_line2, city, geo_lat, geo_lng, contact_phone, contact_email, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, name, code, manager_id, address_line1, address_line2, city, geo_lat, geo_lng, contact_phone, contact_email, is_active, sort_order, created_at, updated_at
`

type CreateHubParams struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	Name         string         `json:"name"`
	Code         sql.NullString `json:"code"`
	ManagerID    pgtype.UUID    `json:"manager_id"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	City         string         `json:"city"`
	GeoLat       pgtype.Numeric `json:"geo_lat"`
	GeoLng       pgtype.Numeric `json:"geo_lng"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	IsActive     bool           `json:"is_active"`
	SortOrder    int32          `json:"sort_order"`
}

func (q *Queries) CreateHub(ctx context.Context, arg CreateHubParams) (Hub, error) {
	row := q.db.QueryRow(ctx, createHub,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.ManagerID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.GeoLat,
		arg.GeoLng,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Hub
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.ManagerID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHubArea = `-- name: CreateHubArea :one
INSERT INTO hub_coverage_areas (hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, geo_polygon, is_active, sort_order
`

type CreateHubAreaParams struct {
	HubID                    uuid.UUID      `json:"hub_id"`
	TenantID                 uuid.UUID      `json:"tenant_id"`
	Name                     string         `json:"name"`
	Slug                     string         `json:"slug"`
	DeliveryCharge           pgtype.Numeric `json:"delivery_charge"`
	MinOrderAmount           pgtype.Numeric `json:"min_order_amount"`
	EstimatedDeliveryMinutes int32          `json:"estimated_delivery_minutes"`
	IsActive                 bool           `json:"is_active"`
	SortOrder                int32          `json:"sort_order"`
}

func (q *Queries) CreateHubArea(ctx context.Context, arg CreateHubAreaParams) (HubCoverageArea, error) {
	row := q.db.QueryRow(ctx, createHubArea,
		arg.HubID,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.DeliveryCharge,
		arg.MinOrderAmount,
		arg.EstimatedDeliveryMinutes,
		arg.IsActive,
		arg.SortOrder,
	)
	var i HubCoverageArea
	err := row.Scan(
		&i.ID,
		&i.HubID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.DeliveryCharge,
		&i.MinOrderAmount,
		&i.EstimatedDeliveryMinutes,
		&i.GeoPolygon,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const deleteHub = `-- name: DeleteHub :exec
DELETE FROM hubs WHERE id = $1 AND tenant_id = $2
`

type DeleteHubParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteHub(ctx context.Context, arg DeleteHubParams) error {
	_, err := q.db.Exec(ctx, deleteHub, arg.ID, arg.TenantID)
	return err
}

const deleteHubArea = `-- name: DeleteHubArea :exec
DELETE FROM hub_coverage_areas WHERE id = $1
`

func (q *Queries) DeleteHubArea(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHubArea, id)
	return err
}

const getDeliveryZoneConfig = `-- name: GetDeliveryZoneConfig :one
SELECT id, tenant_id, model, distance_tiers, free_delivery_threshold, created_at, updated_at FROM delivery_zone_configs WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetDeliveryZoneConfig(ctx context.Context, tenantID uuid.UUID) (DeliveryZoneConfig, error) {
	row := q.db.QueryRow(ctx, getDeliveryZoneConfig, tenantID)
	var i DeliveryZoneConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Model,
		&i.DistanceTiers,
		&i.FreeDeliveryThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHubAreaByID = `-- name: GetHubAreaByID :one
SELECT id, hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, geo_polygon, is_active, sort_order FROM hub_coverage_areas WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHubAreaByID(ctx context.Context, id uuid.UUID) (HubCoverageArea, error) {
	row := q.db.QueryRow(ctx, getHubAreaByID, id)
	var i HubCoverageArea
	err := row.Scan(
		&i.ID,
		&i.HubID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.DeliveryCharge,
		&i.MinOrderAmount,
		&i.EstimatedDeliveryMinutes,
		&i.GeoPolygon,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getHubAreaByName = `-- name: GetHubAreaByName :one
SELECT id, hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, geo_polygon, is_active, sort_order FROM hub_coverage_areas WHERE hub_id = $1 AND slug = $2 LIMIT 1
`

type GetHubAreaByNameParams struct {
	HubID uuid.UUID `json:"hub_id"`
	Slug  string    `json:"slug"`
}

func (q *Queries) GetHubAreaByName(ctx context.Context, arg GetHubAreaByNameParams) (HubCoverageArea, error) {
	row := q.db.QueryRow(ctx, getHubAreaByName, arg.HubID, arg.Slug)
	var i HubCoverageArea
	err := row.Scan(
		&i.ID,
		&i.HubID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.DeliveryCharge,
		&i.MinOrderAmount,
		&i.EstimatedDeliveryMinutes,
		&i.GeoPolygon,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getHubByID = `-- name: GetHubByID :one
SELECT id, tenant_id, name, code, manager_id, address_line1, address_line2, city, geo_lat, geo_lng, contact_phone, contact_email, is_active, sort_order, created_at, updated_at FROM hubs WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetHubByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetHubByID(ctx context.Context, arg GetHubByIDParams) (Hub, error) {
	row := q.db.QueryRow(ctx, getHubByID, arg.ID, arg.TenantID)
	var i Hub
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.ManagerID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHubAreas = `-- name: ListHubAreas :many
SELECT id, hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, geo_polygon, is_active, sort_order FROM hub_coverage_areas WHERE hub_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListHubAreas(ctx context.Context, hubID uuid.UUID) ([]HubCoverageArea, error) {
	rows, err := q.db.Query(ctx, listHubAreas, hubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HubCoverageArea{}
	for rows.Next() {
		var i HubCoverageArea
		if err := rows.Scan(
			&i.ID,
			&i.HubID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.DeliveryCharge,
			&i.MinOrderAmount,
			&i.EstimatedDeliveryMinutes,
			&i.GeoPolygon,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHubsByTenant = `-- name: ListHubsByTenant :many
SELECT id, tenant_id, name, code, manager_id, address_line1, address_line2, city, geo_lat, geo_lng, contact_phone, contact_email, is_active, sort_order, created_at, updated_at FROM hubs WHERE tenant_id = $1 ORDER BY sort_order, name
`

func (q *Queries) ListHubsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Hub, error) {
	rows, err := q.db.Query(ctx, listHubsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hub{}
	for rows.Next() {
		var i Hub
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.ManagerID,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.GeoLat,
			&i.GeoLng,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHub = `-- name: UpdateHub :one
UPDATE hubs SET
  name = COALESCE($1, name),
  code = COALESCE($2, code),
  address_line1 = COALESCE($3, address_line1),
  address_line2 = COALESCE($4, address_line2),
  city = COALESCE($5, city),
  contact_phone = COALESCE($6, contact_phone),
  contact_email = COALESCE($7, contact_email),
  is_active = COALESCE($8, is_active),
  sort_order = COALESCE($9, sort_order)
WHERE id = $10 AND tenant_id = $11
RETURNING id, tenant_id, name, code, manager_id, address_line1, address_line2, city, geo_lat, geo_lng, contact_phone, contact_email, is_active, sort_order, created_at, updated_at
`

type UpdateHubParams struct {
	Name         sql.NullString `json:"name"`
	Code         sql.NullString `json:"code"`
	AddressLine1 sql.NullString `json:"address_line1"`
	AddressLine2 sql.NullString `json:"address_line2"`
	City         sql.NullString `json:"city"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	IsActive     *bool          `json:"is_active"`
	SortOrder    *int32         `json:"sort_order"`
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) UpdateHub(ctx context.Context, arg UpdateHubParams) (Hub, error) {
	row := q.db.QueryRow(ctx, updateHub,
		arg.Name,
		arg.Code,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
		arg.TenantID,
	)
	var i Hub
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.ManagerID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHubArea = `-- name: UpdateHubArea :one
UPDATE hub_coverage_areas SET
  name = COALESCE($1, name),
  delivery_charge = COALESCE($2, delivery_charge),
  min_order_amount = COALESCE($3, min_order_amount),
  estimated_delivery_minutes = COALESCE($4, estimated_delivery_minutes),
  is_active = COALESCE($5, is_active),
  sort_order = COALESCE($6, sort_order)
WHERE id = $7
RETURNING id, hub_id, tenant_id, name, slug, delivery_charge, min_order_amount, estimated_delivery_minutes, geo_polygon, is_active, sort_order
`

type UpdateHubAreaParams struct {
	Name                     sql.NullString `json:"name"`
	DeliveryCharge           pgtype.Numeric `json:"delivery_charge"`
	MinOrderAmount           pgtype.Numeric `json:"min_order_amount"`
	EstimatedDeliveryMinutes *int32         `json:"estimated_delivery_minutes"`
	IsActive                 *bool          `json:"is_active"`
	SortOrder                *int32         `json:"sort_order"`
	ID                       uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateHubArea(ctx context.Context, arg UpdateHubAreaParams) (HubCoverageArea, error) {
	row := q.db.QueryRow(ctx, updateHubArea,
		arg.Name,
		arg.DeliveryCharge,
		arg.MinOrderAmount,
		arg.EstimatedDeliveryMinutes,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i HubCoverageArea
	err := row.Scan(
		&i.ID,
		&i.HubID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.DeliveryCharge,
		&i.MinOrderAmount,
		&i.EstimatedDeliveryMinutes,
		&i.GeoPolygon,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const upsertDeliveryZoneConfig = `-- name: UpsertDeliveryZoneConfig :one
INSERT INTO delivery_zone_configs (tenant_id, model, distance_tiers, free_delivery_threshold)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO UPDATE SET
  model = EXCLUDED.model,
  distance_tiers = EXCLUDED.distance_tiers,
  free_delivery_threshold = EXCLUDED.free_delivery_threshold
RETURNING id, tenant_id, model, distance_tiers, free_delivery_threshold, created_at, updated_at
`

type UpsertDeliveryZoneConfigParams struct {
	TenantID              uuid.UUID       `json:"tenant_id"`
	Model                 DeliveryModel   `json:"model"`
	DistanceTiers         json.RawMessage `json:"distance_tiers"`
	FreeDeliveryThreshold pgtype.Numeric  `json:"free_delivery_threshold"`
}

func (q *Queries) UpsertDeliveryZoneConfig(ctx context.Context, arg UpsertDeliveryZoneConfigParams) (DeliveryZoneConfig, error) {
	row := q.db.QueryRow(ctx, upsertDeliveryZoneConfig,
		arg.TenantID,
		arg.Model,
		arg.DistanceTiers,
		arg.FreeDeliveryThreshold,
	)
	var i DeliveryZoneConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Model,
		&i.DistanceTiers,
		&i.FreeDeliveryThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
