// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: idempotency_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (tenant_id, user_id, key, endpoint, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, user_id, key, endpoint, request_hash, response_status, response_body, expires_at, created_at
`

type CreateIdempotencyKeyParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Key         string      `json:"key"`
	Endpoint    string      `json:"endpoint"`
	RequestHash string      `json:"request_hash"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.TenantID,
		arg.UserID,
		arg.Key,
		arg.Endpoint,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, tenant_id, user_id, key, endpoint, request_hash, response_status, response_body, expires_at, created_at FROM idempotency_keys
WHERE tenant_id IS NOT DISTINCT FROM $1
  AND user_id IS NOT DISTINCT FROM $2
  AND key = $3
  AND endpoint = $4
LIMIT 1
`

type GetIdempotencyKeyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Key      string      `json:"key"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.TenantID,
		arg.UserID,
		arg.Key,
		arg.Endpoint,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :exec
UPDATE idempotency_keys SET response_status = $2, response_body = $3 WHERE id = $1
`

type UpdateIdempotencyKeyResponseParams struct {
	ID             uuid.UUID `json:"id"`
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKeyResponse, arg.ID, arg.ResponseStatus, arg.ResponseBody)
	return err
}
