// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger_accounts (code, name, account_type, description, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, account_type, description, is_system, created_at
`

type CreateLedgerAccountParams struct {
	Code        string            `json:"code"`
	Name        string            `json:"name"`
	AccountType LedgerAccountType `json:"account_type"`
	Description sql.NullString    `json:"description"`
	IsSystem    bool              `json:"is_system"`
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.Description,
		arg.IsSystem,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    tenant_id, account_id, entry_type, reference_type, reference_id,
    debit, credit, balance_after, description, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, account_id, entry_type, reference_type, reference_id, debit, credit, balance_after, description, metadata, created_at
`

type CreateLedgerEntryParams struct {
	TenantID      pgtype.UUID     `json:"tenant_id"`
	AccountID     uuid.UUID       `json:"account_id"`
	EntryType     LedgerEntryType `json:"entry_type"`
	ReferenceType string          `json:"reference_type"`
	ReferenceID   uuid.UUID       `json:"reference_id"`
	Debit         pgtype.Numeric  `json:"debit"`
	Credit        pgtype.Numeric  `json:"credit"`
	BalanceAfter  pgtype.Numeric  `json:"balance_after"`
	Description   string          `json:"description"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.TenantID,
		arg.AccountID,
		arg.EntryType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Debit,
		arg.Credit,
		arg.BalanceAfter,
		arg.Description,
		arg.Metadata,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.EntryType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Debit,
		&i.Credit,
		&i.BalanceAfter,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLastLedgerEntryBalance = `-- name: GetLastLedgerEntryBalance :one
SELECT balance_after FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastLedgerEntryBalance(ctx context.Context, accountID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLastLedgerEntryBalance, accountID)
	var balance_after pgtype.Numeric
	err := row.Scan(&balance_after)
	return balance_after, err
}

const getLedgerAccountByCode = `-- name: GetLedgerAccountByCode :one
SELECT id, code, name, account_type, description, is_system, created_at FROM ledger_accounts WHERE code = $1 LIMIT 1
`

func (q *Queries) GetLedgerAccountByCode(ctx context.Context, code string) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByCode, code)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, code, name, account_type, description, is_system, created_at FROM ledger_accounts ORDER BY code
`

func (q *Queries) ListLedgerAccounts(ctx context.Context) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccount{}
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, tenant_id, account_id, entry_type, reference_type, reference_id, debit, credit, balance_after, description, metadata, created_at FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.EntryType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Debit,
			&i.Credit,
			&i.BalanceAfter,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByReference = `-- name: ListLedgerEntriesByReference :many
SELECT id, tenant_id, account_id, entry_type, reference_type, reference_id, debit, credit, balance_after, description, metadata, created_at FROM ledger_entries
WHERE reference_type = $1 AND reference_id = $2
ORDER BY created_at ASC
`

type ListLedgerEntriesByReferenceParams struct {
	ReferenceType string    `json:"reference_type"`
	ReferenceID   uuid.UUID `json:"reference_id"`
}

func (q *Queries) ListLedgerEntriesByReference(ctx context.Context, arg ListLedgerEntriesByReferenceParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.EntryType,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Debit,
			&i.Credit,
			&i.BalanceAfter,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
