// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
)

type Accountable string

const (
	AccountableRestaurant Accountable = "restaurant"
	AccountableRider      Accountable = "rider"
	AccountablePlatform   Accountable = "platform"
)

func (e *Accountable) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Accountable(s)
	case string:
		*e = Accountable(s)
	default:
		return fmt.Errorf("unsupported scan type for Accountable: %T", src)
	}
	return nil
}

type NullAccountable struct {
	Accountable Accountable `json:"accountable"`
	Valid       bool        `json:"valid"` // Valid is true if Accountable is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountable) Scan(value interface{}) error {
	if value == nil {
		ns.Accountable, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Accountable.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountable) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Accountable), nil
}

type DeliveryModel string

const (
	DeliveryModelZoneBased     DeliveryModel = "zone_based"
	DeliveryModelDistanceBased DeliveryModel = "distance_based"
)

func (e *DeliveryModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryModel(s)
	case string:
		*e = DeliveryModel(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryModel: %T", src)
	}
	return nil
}

type NullDeliveryModel struct {
	DeliveryModel DeliveryModel `json:"delivery_model"`
	Valid         bool          `json:"valid"` // Valid is true if DeliveryModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryModel) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryModel), nil
}

type DiscountType string

const (
	DiscountTypeFixed   DiscountType = "fixed"
	DiscountTypePercent DiscountType = "percent"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discount_type"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft     InvoiceStatus = "draft"
	InvoiceStatusFinalized InvoiceStatus = "finalized"
	InvoiceStatusPaid      InvoiceStatus = "paid"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type IssueStatus string

const (
	IssueStatusOpen     IssueStatus = "open"
	IssueStatusResolved IssueStatus = "resolved"
	IssueStatusClosed   IssueStatus = "closed"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus `json:"issue_status"`
	Valid       bool        `json:"valid"` // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type IssueType string

const (
	IssueTypeWrongItem    IssueType = "wrong_item"
	IssueTypeMissingItem  IssueType = "missing_item"
	IssueTypeQualityIssue IssueType = "quality_issue"
	IssueTypeLateDelivery IssueType = "late_delivery"
	IssueTypeOther        IssueType = "other"
)

func (e *IssueType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueType(s)
	case string:
		*e = IssueType(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueType: %T", src)
	}
	return nil
}

type NullIssueType struct {
	IssueType IssueType `json:"issue_type"`
	Valid     bool      `json:"valid"` // Valid is true if IssueType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueType) Scan(value interface{}) error {
	if value == nil {
		ns.IssueType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueType), nil
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusCreated   OrderStatus = "created"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusPicked    OrderStatus = "picked"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusRejected  OrderStatus = "rejected"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCod        PaymentMethod = "cod"
	PaymentMethodBkash      PaymentMethod = "bkash"
	PaymentMethodAamarpay   PaymentMethod = "aamarpay"
	PaymentMethodSslcommerz PaymentMethod = "sslcommerz"
	PaymentMethodWallet     PaymentMethod = "wallet"
	PaymentMethodCard       PaymentMethod = "card"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid            PaymentStatus = "unpaid"
	PaymentStatusPaid              PaymentStatus = "paid"
	PaymentStatusRefunded          PaymentStatus = "refunded"
	PaymentStatusPartiallyRefunded PaymentStatus = "partially_refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PenaltyStatus string

const (
	PenaltyStatusPending  PenaltyStatus = "pending"
	PenaltyStatusCleared  PenaltyStatus = "cleared"
	PenaltyStatusAppealed PenaltyStatus = "appealed"
)

func (e *PenaltyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PenaltyStatus(s)
	case string:
		*e = PenaltyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PenaltyStatus: %T", src)
	}
	return nil
}

type NullPenaltyStatus struct {
	PenaltyStatus PenaltyStatus `json:"penalty_status"`
	Valid         bool          `json:"valid"` // Valid is true if PenaltyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPenaltyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PenaltyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PenaltyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPenaltyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PenaltyStatus), nil
}

type PickupStatus string

const (
	PickupStatusNew       PickupStatus = "new"
	PickupStatusConfirmed PickupStatus = "confirmed"
	PickupStatusPreparing PickupStatus = "preparing"
	PickupStatusReady     PickupStatus = "ready"
	PickupStatusPicked    PickupStatus = "picked"
	PickupStatusRejected  PickupStatus = "rejected"
)

func (e *PickupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PickupStatus(s)
	case string:
		*e = PickupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PickupStatus: %T", src)
	}
	return nil
}

type NullPickupStatus struct {
	PickupStatus PickupStatus `json:"pickup_status"`
	Valid        bool         `json:"valid"` // Valid is true if PickupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPickupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PickupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PickupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPickupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PickupStatus), nil
}

type PlatformSource string

const (
	PlatformSourceWeb     PlatformSource = "web"
	PlatformSourceIos     PlatformSource = "ios"
	PlatformSourceAndroid PlatformSource = "android"
	PlatformSourcePos     PlatformSource = "pos"
)

func (e *PlatformSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformSource(s)
	case string:
		*e = PlatformSource(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformSource: %T", src)
	}
	return nil
}

type NullPlatformSource struct {
	PlatformSource PlatformSource `json:"platform_source"`
	Valid          bool           `json:"valid"` // Valid is true if PlatformSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformSource) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformSource), nil
}

type PriceType string

const (
	PriceTypeFlat    PriceType = "flat"
	PriceTypeVariant PriceType = "variant"
)

func (e *PriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceType(s)
	case string:
		*e = PriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceType: %T", src)
	}
	return nil
}

type NullPriceType struct {
	PriceType PriceType `json:"price_type"`
	Valid     bool      `json:"valid"` // Valid is true if PriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceType), nil
}

type ProductAvail string

const (
	ProductAvailAvailable   ProductAvail = "available"
	ProductAvailUnavailable ProductAvail = "unavailable"
	ProductAvailOutOfStock  ProductAvail = "out_of_stock"
)

func (e *ProductAvail) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductAvail(s)
	case string:
		*e = ProductAvail(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductAvail: %T", src)
	}
	return nil
}

type NullProductAvail struct {
	ProductAvail ProductAvail `json:"product_avail"`
	Valid        bool         `json:"valid"` // Valid is true if ProductAvail is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductAvail) Scan(value interface{}) error {
	if value == nil {
		ns.ProductAvail, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductAvail.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductAvail) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductAvail), nil
}

type PromoApplyOn string

const (
	PromoApplyOnAllItems           PromoApplyOn = "all_items"
	PromoApplyOnCategory           PromoApplyOn = "category"
	PromoApplyOnSpecificRestaurant PromoApplyOn = "specific_restaurant"
	PromoApplyOnDeliveryCharge     PromoApplyOn = "delivery_charge"
)

func (e *PromoApplyOn) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoApplyOn(s)
	case string:
		*e = PromoApplyOn(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoApplyOn: %T", src)
	}
	return nil
}

type NullPromoApplyOn struct {
	PromoApplyOn PromoApplyOn `json:"promo_apply_on"`
	Valid        bool         `json:"valid"` // Valid is true if PromoApplyOn is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoApplyOn) Scan(value interface{}) error {
	if value == nil {
		ns.PromoApplyOn, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoApplyOn.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoApplyOn) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoApplyOn), nil
}

type PromoFunder string

const (
	PromoFunderVendor     PromoFunder = "vendor"
	PromoFunderPlatform   PromoFunder = "platform"
	PromoFunderRestaurant PromoFunder = "restaurant"
)

func (e *PromoFunder) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoFunder(s)
	case string:
		*e = PromoFunder(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoFunder: %T", src)
	}
	return nil
}

type NullPromoFunder struct {
	PromoFunder PromoFunder `json:"promo_funder"`
	Valid       bool        `json:"valid"` // Valid is true if PromoFunder is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoFunder) Scan(value interface{}) error {
	if value == nil {
		ns.PromoFunder, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoFunder.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoFunder) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoFunder), nil
}

type PromoType string

const (
	PromoTypeFixed   PromoType = "fixed"
	PromoTypePercent PromoType = "percent"
)

func (e *PromoType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoType(s)
	case string:
		*e = PromoType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoType: %T", src)
	}
	return nil
}

type NullPromoType struct {
	PromoType PromoType `json:"promo_type"`
	Valid     bool      `json:"valid"` // Valid is true if PromoType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoType) Scan(value interface{}) error {
	if value == nil {
		ns.PromoType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoType), nil
}

type RefundStatus string

const (
	RefundStatusPending   RefundStatus = "pending"
	RefundStatusApproved  RefundStatus = "approved"
	RefundStatusRejected  RefundStatus = "rejected"
	RefundStatusProcessed RefundStatus = "processed"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus `json:"refund_status"`
	Valid        bool         `json:"valid"` // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type RestaurantType string

const (
	RestaurantTypeRestaurant   RestaurantType = "restaurant"
	RestaurantTypeCloudKitchen RestaurantType = "cloud_kitchen"
	RestaurantTypeStore        RestaurantType = "store"
	RestaurantTypeDarkStore    RestaurantType = "dark_store"
)

func (e *RestaurantType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RestaurantType(s)
	case string:
		*e = RestaurantType(s)
	default:
		return fmt.Errorf("unsupported scan type for RestaurantType: %T", src)
	}
	return nil
}

type NullRestaurantType struct {
	RestaurantType RestaurantType `json:"restaurant_type"`
	Valid          bool           `json:"valid"` // Valid is true if RestaurantType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRestaurantType) Scan(value interface{}) error {
	if value == nil {
		ns.RestaurantType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RestaurantType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRestaurantType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RestaurantType), nil
}

type RiderSubject string

const (
	RiderSubjectAttendanceIn   RiderSubject = "attendance_in"
	RiderSubjectAttendanceOut  RiderSubject = "attendance_out"
	RiderSubjectPicked         RiderSubject = "picked"
	RiderSubjectDelivered      RiderSubject = "delivered"
	RiderSubjectInHub          RiderSubject = "in_hub"
	RiderSubjectLocationUpdate RiderSubject = "location_update"
)

func (e *RiderSubject) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderSubject(s)
	case string:
		*e = RiderSubject(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderSubject: %T", src)
	}
	return nil
}

type NullRiderSubject struct {
	RiderSubject RiderSubject `json:"rider_subject"`
	Valid        bool         `json:"valid"` // Valid is true if RiderSubject is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderSubject) Scan(value interface{}) error {
	if value == nil {
		ns.RiderSubject, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderSubject.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderSubject) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderSubject), nil
}

type TenantPlan string

const (
	TenantPlanStarter    TenantPlan = "starter"
	TenantPlanGrowth     TenantPlan = "growth"
	TenantPlanEnterprise TenantPlan = "enterprise"
)

func (e *TenantPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantPlan(s)
	case string:
		*e = TenantPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantPlan: %T", src)
	}
	return nil
}

type NullTenantPlan struct {
	TenantPlan TenantPlan `json:"tenant_plan"`
	Valid      bool       `json:"valid"` // Valid is true if TenantPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantPlan) Scan(value interface{}) error {
	if value == nil {
		ns.TenantPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantPlan), nil
}

type TenantStatus string

const (
	TenantStatusPending   TenantStatus = "pending"
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusCancelled TenantStatus = "cancelled"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type TxnStatus string

const (
	TxnStatusPending   TxnStatus = "pending"
	TxnStatusSuccess   TxnStatus = "success"
	TxnStatusFailed    TxnStatus = "failed"
	TxnStatusRefunded  TxnStatus = "refunded"
	TxnStatusCancelled TxnStatus = "cancelled"
)

func (e *TxnStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxnStatus(s)
	case string:
		*e = TxnStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxnStatus: %T", src)
	}
	return nil
}

type NullTxnStatus struct {
	TxnStatus TxnStatus `json:"txn_status"`
	Valid     bool      `json:"valid"` // Valid is true if TxnStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxnStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxnStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxnStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxnStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxnStatus), nil
}

type UserRole string

const (
	UserRoleCustomer          UserRole = "customer"
	UserRoleTenantOwner       UserRole = "tenant_owner"
	UserRoleTenantAdmin       UserRole = "tenant_admin"
	UserRoleRestaurantManager UserRole = "restaurant_manager"
	UserRoleRestaurantStaff   UserRole = "restaurant_staff"
	UserRoleRider             UserRole = "rider"
	UserRolePlatformAdmin     UserRole = "platform_admin"
	UserRolePlatformSupport   UserRole = "platform_support"
	UserRolePlatformFinance   UserRole = "platform_finance"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type VehicleType string

const (
	VehicleTypeBicycle    VehicleType = "bicycle"
	VehicleTypeMotorcycle VehicleType = "motorcycle"
	VehicleTypeCar        VehicleType = "car"
)

func (e *VehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleType(s)
	case string:
		*e = VehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleType: %T", src)
	}
	return nil
}

type NullVehicleType struct {
	VehicleType VehicleType `json:"vehicle_type"`
	Valid       bool        `json:"valid"` // Valid is true if VehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleType), nil
}

type WalletSource string

const (
	WalletSourceCashback        WalletSource = "cashback"
	WalletSourceReferral        WalletSource = "referral"
	WalletSourceWelcome         WalletSource = "welcome"
	WalletSourceRefund          WalletSource = "refund"
	WalletSourceOrderPayment    WalletSource = "order_payment"
	WalletSourceAdminAdjustment WalletSource = "admin_adjustment"
)

func (e *WalletSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletSource(s)
	case string:
		*e = WalletSource(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletSource: %T", src)
	}
	return nil
}

type NullWalletSource struct {
	WalletSource WalletSource `json:"wallet_source"`
	Valid        bool         `json:"valid"` // Valid is true if WalletSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletSource) Scan(value interface{}) error {
	if value == nil {
		ns.WalletSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletSource), nil
}

type WalletType string

const (
	WalletTypeCredit WalletType = "credit"
	WalletTypeDebit  WalletType = "debit"
)

func (e *WalletType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletType(s)
	case string:
		*e = WalletType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletType: %T", src)
	}
	return nil
}

type NullWalletType struct {
	WalletType WalletType `json:"wallet_type"`
	Valid      bool       `json:"valid"` // Valid is true if WalletType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletType), nil
}
