// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, tenant_id, user_id, channel, title, body, image_url, action_type, action_payload, status, sent_at, delivered_at, read_at, failed_reason, gateway_message_id, created_at FROM notifications WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetNotificationByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionType,
		&i.ActionPayload,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedReason,
		&i.GatewayMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, channel, title, body, image_url, action_type, action_payload, status, sent_at, delivered_at, read_at, failed_reason, gateway_message_id, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Channel,
			&i.Title,
			&i.Body,
			&i.ImageUrl,
			&i.ActionType,
			&i.ActionPayload,
			&i.Status,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ReadAt,
			&i.FailedReason,
			&i.GatewayMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET status = 'read' WHERE id = $1 AND user_id = $2 RETURNING id, tenant_id, user_id, channel, title, body, image_url, action_type, action_payload, status, sent_at, delivered_at, read_at, failed_reason, gateway_message_id, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Channel,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionType,
		&i.ActionPayload,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ReadAt,
		&i.FailedReason,
		&i.GatewayMessageID,
		&i.CreatedAt,
	)
	return i, err
}
