// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_pickups.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getPickupByOrderAndRestaurant = `-- name: GetPickupByOrderAndRestaurant :one
SELECT id, order_id, restaurant_id, tenant_id, pickup_number, status, items_subtotal, items_discount, items_vat, items_total, commission_rate, commission_amount, confirmed_at, preparing_at, ready_at, picked_at, rejected_at, rejection_reason, created_at, updated_at FROM order_pickups
WHERE order_id = $1 AND restaurant_id = $2 AND tenant_id = $3
LIMIT 1
`

type GetPickupByOrderAndRestaurantParams struct {
	OrderID      uuid.UUID `json:"order_id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPickupByOrderAndRestaurant(ctx context.Context, arg GetPickupByOrderAndRestaurantParams) (OrderPickup, error) {
	row := q.db.QueryRow(ctx, getPickupByOrderAndRestaurant, arg.OrderID, arg.RestaurantID, arg.TenantID)
	var i OrderPickup
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RestaurantID,
		&i.TenantID,
		&i.PickupNumber,
		&i.Status,
		&i.ItemsSubtotal,
		&i.ItemsDiscount,
		&i.ItemsVat,
		&i.ItemsTotal,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.ConfirmedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.PickedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPickupsByOrder = `-- name: ListPickupsByOrder :many
SELECT id, order_id, restaurant_id, tenant_id, pickup_number, status, items_subtotal, items_discount, items_vat, items_total, commission_rate, commission_amount, confirmed_at, preparing_at, ready_at, picked_at, rejected_at, rejection_reason, created_at, updated_at FROM order_pickups WHERE order_id = $1 AND tenant_id = $2
`

type ListPickupsByOrderParams struct {
	OrderID  uuid.UUID `json:"order_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListPickupsByOrder(ctx context.Context, arg ListPickupsByOrderParams) ([]OrderPickup, error) {
	rows, err := q.db.Query(ctx, listPickupsByOrder, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderPickup{}
	for rows.Next() {
		var i OrderPickup
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.RestaurantID,
			&i.TenantID,
			&i.PickupNumber,
			&i.Status,
			&i.ItemsSubtotal,
			&i.ItemsDiscount,
			&i.ItemsVat,
			&i.ItemsTotal,
			&i.CommissionRate,
			&i.CommissionAmount,
			&i.ConfirmedAt,
			&i.PreparingAt,
			&i.ReadyAt,
			&i.PickedAt,
			&i.RejectedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePickupStatus = `-- name: UpdatePickupStatus :one
UPDATE order_pickups SET status = $3, picked_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, order_id, restaurant_id, tenant_id, pickup_number, status, items_subtotal, items_discount, items_vat, items_total, commission_rate, commission_amount, confirmed_at, preparing_at, ready_at, picked_at, rejected_at, rejection_reason, created_at, updated_at
`

type UpdatePickupStatusParams struct {
	ID       uuid.UUID    `json:"id"`
	TenantID uuid.UUID    `json:"tenant_id"`
	Status   PickupStatus `json:"status"`
}

func (q *Queries) UpdatePickupStatus(ctx context.Context, arg UpdatePickupStatusParams) (OrderPickup, error) {
	row := q.db.QueryRow(ctx, updatePickupStatus, arg.ID, arg.TenantID, arg.Status)
	var i OrderPickup
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RestaurantID,
		&i.TenantID,
		&i.PickupNumber,
		&i.Status,
		&i.ItemsSubtotal,
		&i.ItemsDiscount,
		&i.ItemsVat,
		&i.ItemsTotal,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.ConfirmedAt,
		&i.PreparingAt,
		&i.ReadyAt,
		&i.PickedAt,
		&i.RejectedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
