// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_timeline.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimelineEvent = `-- name: CreateTimelineEvent :one
INSERT INTO order_timeline_events (
    order_id, tenant_id, event_type, previous_status, new_status,
    description, actor_id, actor_type, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, order_id, tenant_id, event_type, previous_status, new_status, description, actor_id, actor_type, metadata, created_at
`

type CreateTimelineEventParams struct {
	OrderID        uuid.UUID       `json:"order_id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	EventType      string          `json:"event_type"`
	PreviousStatus NullOrderStatus `json:"previous_status"`
	NewStatus      NullOrderStatus `json:"new_status"`
	Description    string          `json:"description"`
	ActorID        pgtype.UUID     `json:"actor_id"`
	ActorType      ActorType       `json:"actor_type"`
	Metadata       json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (OrderTimelineEvent, error) {
	row := q.db.QueryRow(ctx, createTimelineEvent,
		arg.OrderID,
		arg.TenantID,
		arg.EventType,
		arg.PreviousStatus,
		arg.NewStatus,
		arg.Description,
		arg.ActorID,
		arg.ActorType,
		arg.Metadata,
	)
	var i OrderTimelineEvent
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TenantID,
		&i.EventType,
		&i.PreviousStatus,
		&i.NewStatus,
		&i.Description,
		&i.ActorID,
		&i.ActorType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listTimelineByOrder = `-- name: ListTimelineByOrder :many
SELECT id, order_id, tenant_id, event_type, previous_status, new_status, description, actor_id, actor_type, metadata, created_at FROM order_timeline_events
WHERE order_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
`

type ListTimelineByOrderParams struct {
	OrderID  uuid.UUID `json:"order_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListTimelineByOrder(ctx context.Context, arg ListTimelineByOrderParams) ([]OrderTimelineEvent, error) {
	rows, err := q.db.Query(ctx, listTimelineByOrder, arg.OrderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderTimelineEvent{}
	for rows.Next() {
		var i OrderTimelineEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TenantID,
			&i.EventType,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.Description,
			&i.ActorID,
			&i.ActorType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
