// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_issues.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createOrderIssue = `-- name: CreateOrderIssue :one
INSERT INTO order_issues (
    order_id, tenant_id, issue_type, reported_by_id, details,
    accountable_party
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, tenant_id, issue_type, reported_by_id, details, evidence_urls, accountable_party, refund_items, refund_amount, refund_status, restaurant_penalty_amount, rider_penalty_amount, status, resolution_note, resolved_by_id, resolved_at, created_at, updated_at
`

type CreateOrderIssueParams struct {
	OrderID          uuid.UUID   `json:"order_id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	IssueType        IssueType   `json:"issue_type"`
	ReportedByID     uuid.UUID   `json:"reported_by_id"`
	Details          string      `json:"details"`
	AccountableParty Accountable `json:"accountable_party"`
}

func (q *Queries) CreateOrderIssue(ctx context.Context, arg CreateOrderIssueParams) (OrderIssue, error) {
	row := q.db.QueryRow(ctx, createOrderIssue,
		arg.OrderID,
		arg.TenantID,
		arg.IssueType,
		arg.ReportedByID,
		arg.Details,
		arg.AccountableParty,
	)
	var i OrderIssue
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TenantID,
		&i.IssueType,
		&i.ReportedByID,
		&i.Details,
		&i.EvidenceUrls,
		&i.AccountableParty,
		&i.RefundItems,
		&i.RefundAmount,
		&i.RefundStatus,
		&i.RestaurantPenaltyAmount,
		&i.RiderPenaltyAmount,
		&i.Status,
		&i.ResolutionNote,
		&i.ResolvedByID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderIssueByID = `-- name: GetOrderIssueByID :one
SELECT id, order_id, tenant_id, issue_type, reported_by_id, details, evidence_urls, accountable_party, refund_items, refund_amount, refund_status, restaurant_penalty_amount, rider_penalty_amount, status, resolution_note, resolved_by_id, resolved_at, created_at, updated_at FROM order_issues WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetOrderIssueByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetOrderIssueByID(ctx context.Context, arg GetOrderIssueByIDParams) (OrderIssue, error) {
	row := q.db.QueryRow(ctx, getOrderIssueByID, arg.ID, arg.TenantID)
	var i OrderIssue
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TenantID,
		&i.IssueType,
		&i.ReportedByID,
		&i.Details,
		&i.EvidenceUrls,
		&i.AccountableParty,
		&i.RefundItems,
		&i.RefundAmount,
		&i.RefundStatus,
		&i.RestaurantPenaltyAmount,
		&i.RiderPenaltyAmount,
		&i.Status,
		&i.ResolutionNote,
		&i.ResolvedByID,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
