// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: otp_verifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentOTPs = `-- name: CountRecentOTPs :one
SELECT COUNT(*) FROM otp_verifications
WHERE phone = $1 AND purpose = $2 AND created_at > $3
`

type CountRecentOTPsParams struct {
	Phone     string    `json:"phone"`
	Purpose   string    `json:"purpose"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPs, arg.Phone, arg.Purpose, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTPVerification = `-- name: CreateOTPVerification :one
INSERT INTO otp_verifications (tenant_id, phone, purpose, otp_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, phone, purpose, otp_hash, attempts, max_attempts, expires_at, verified_at, created_at
`

type CreateOTPVerificationParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Phone     string      `json:"phone"`
	Purpose   string      `json:"purpose"`
	OtpHash   string      `json:"otp_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateOTPVerification(ctx context.Context, arg CreateOTPVerificationParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, createOTPVerification,
		arg.TenantID,
		arg.Phone,
		arg.Purpose,
		arg.OtpHash,
		arg.ExpiresAt,
	)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.Purpose,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, tenant_id, phone, purpose, otp_hash, attempts, max_attempts, expires_at, verified_at, created_at FROM otp_verifications
WHERE phone = $1 AND purpose = $2 AND verified_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.Phone, arg.Purpose)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.Purpose,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_verifications SET attempts = attempts + 1 WHERE id = $1 RETURNING id, tenant_id, phone, purpose, otp_hash, attempts, max_attempts, expires_at, verified_at, created_at
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Phone,
		&i.Purpose,
		&i.OtpHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_verifications SET verified_at = NOW() WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}
