// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	// Hub queries
	CreateHub(ctx context.Context, arg CreateHubParams) (Hub, error)
	GetHubByID(ctx context.Context, arg GetHubByIDParams) (Hub, error)
	ListHubsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Hub, error)
	UpdateHub(ctx context.Context, arg UpdateHubParams) (Hub, error)
	DeleteHub(ctx context.Context, arg DeleteHubParams) error
	CreateHubArea(ctx context.Context, arg CreateHubAreaParams) (HubCoverageArea, error)
	GetHubAreaByID(ctx context.Context, id uuid.UUID) (HubCoverageArea, error)
	GetHubAreaByName(ctx context.Context, arg GetHubAreaByNameParams) (HubCoverageArea, error)
	ListHubAreas(ctx context.Context, hubID uuid.UUID) ([]HubCoverageArea, error)
	UpdateHubArea(ctx context.Context, arg UpdateHubAreaParams) (HubCoverageArea, error)
	DeleteHubArea(ctx context.Context, id uuid.UUID) error
	GetDeliveryZoneConfig(ctx context.Context, tenantID uuid.UUID) (DeliveryZoneConfig, error)
	UpsertDeliveryZoneConfig(ctx context.Context, arg UpsertDeliveryZoneConfigParams) (DeliveryZoneConfig, error)
	// Restaurant queries
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	GetRestaurantByID(ctx context.Context, arg GetRestaurantByIDParams) (Restaurant, error)
	GetRestaurantBySlug(ctx context.Context, arg GetRestaurantBySlugParams) (Restaurant, error)
	ListRestaurantsByTenant(ctx context.Context, arg ListRestaurantsByTenantParams) ([]Restaurant, error)
	CountRestaurantsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	ListAvailableByHubAndArea(ctx context.Context, arg ListAvailableByHubAndAreaParams) ([]Restaurant, error)
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error)
	UpdateRestaurantAvailability(ctx context.Context, arg UpdateRestaurantAvailabilityParams) (Restaurant, error)
	DeleteRestaurant(ctx context.Context, arg DeleteRestaurantParams) error
	UpsertOperatingHour(ctx context.Context, arg UpsertOperatingHourParams) (RestaurantOperatingHour, error)
	ListOperatingHours(ctx context.Context, restaurantID uuid.UUID) ([]RestaurantOperatingHour, error)
	DeleteOperatingHours(ctx context.Context, restaurantID uuid.UUID) error
	// Category queries
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	ListCategoriesByRestaurant(ctx context.Context, arg ListCategoriesByRestaurantParams) ([]Category, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error
	// Product queries
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductByIDPublic(ctx context.Context, id uuid.UUID) (Product, error)
	ListProductsByRestaurant(ctx context.Context, arg ListProductsByRestaurantParams) ([]Product, error)
	CountProductsByRestaurant(ctx context.Context, arg CountProductsByRestaurantParams) (int64, error)
	ListAvailableProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (Product, error)
	UpdateProductHasModifiers(ctx context.Context, arg UpdateProductHasModifiersParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	// Modifier group/option queries
	CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ProductModifierGroup, error)
	GetModifierGroupByID(ctx context.Context, id uuid.UUID) (ProductModifierGroup, error)
	ListModifierGroupsByProduct(ctx context.Context, productID uuid.UUID) ([]ProductModifierGroup, error)
	UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ProductModifierGroup, error)
	DeleteModifierGroup(ctx context.Context, id uuid.UUID) error
	CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ProductModifierOption, error)
	ListModifierOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]ProductModifierOption, error)
	UpdateModifierOption(ctx context.Context, arg UpdateModifierOptionParams) (ProductModifierOption, error)
	DeleteModifierOption(ctx context.Context, id uuid.UUID) error
	DeleteModifierOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) error
	// Discount queries
	UpsertProductDiscount(ctx context.Context, arg UpsertProductDiscountParams) (ProductDiscount, error)
	GetActiveDiscount(ctx context.Context, productID uuid.UUID) (ProductDiscount, error)
	DeactivateProductDiscount(ctx context.Context, productID uuid.UUID) error
	ExpireDiscounts(ctx context.Context) error
	// Existing queries
	ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error
	CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error)
	CountWalletTransactions(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOTPVerification(ctx context.Context, arg CreateOTPVerificationParams) (OtpVerification, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (UserAddress, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpVerification, error)
	GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTenantByDomain(ctx context.Context, customDomain sql.NullString) (Tenant, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, arg GetUserByPhoneParams) (User, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpVerification, error)
	ListAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	MarkOTPVerified(ctx context.Context, id uuid.UUID) error
	// placeholder query to validate SQLC pipeline
	Ping(ctx context.Context) (int32, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error)
	UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
