// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AppealPenalty(ctx context.Context, arg AppealPenaltyParams) (RiderPenalty, error)
	AppendLocationHistory(ctx context.Context, arg AppendLocationHistoryParams) (RiderLocationHistory, error)
	ApproveRefund(ctx context.Context, arg ApproveRefundParams) (Refund, error)
	AssignRiderToOrder(ctx context.Context, arg AssignRiderToOrderParams) (Order, error)
	ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error
	ClearUserPushToken(ctx context.Context, id uuid.UUID) error
	CountBannersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountInvoicesByRestaurant(ctx context.Context, arg CountInvoicesByRestaurantParams) (int64, error)
	CountInvoicesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOrderIssuesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountOrdersByRestaurantAndPeriod(ctx context.Context, arg CountOrdersByRestaurantAndPeriodParams) (CountOrdersByRestaurantAndPeriodRow, error)
	CountProductsByRestaurant(ctx context.Context, arg CountProductsByRestaurantParams) (int64, error)
	CountRecentOTPs(ctx context.Context, arg CountRecentOTPsParams) (int64, error)
	CountRestaurantsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountReviewsByRestaurant(ctx context.Context, arg CountReviewsByRestaurantParams) (int64, error)
	CountRidersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountStoriesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountWalletTransactions(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error)
	CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (RiderAttendance, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBanner(ctx context.Context, arg CreateBannerParams) (Banner, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateHub(ctx context.Context, arg CreateHubParams) (Hub, error)
	CreateHubArea(ctx context.Context, arg CreateHubAreaParams) (HubCoverageArea, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ProductModifierGroup, error)
	CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ProductModifierOption, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOTPVerification(ctx context.Context, arg CreateOTPVerificationParams) (OtpVerification, error)
	CreateOrderAnalytics(ctx context.Context, arg CreateOrderAnalyticsParams) (OrderAnalytic, error)
	CreateOrderIssue(ctx context.Context, arg CreateOrderIssueParams) (OrderIssue, error)
	CreateOrderIssueMessage(ctx context.Context, arg CreateOrderIssueMessageParams) (OrderIssueMessage, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (Refund, error)
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateRider(ctx context.Context, arg CreateRiderParams) (Rider, error)
	CreateRiderEarning(ctx context.Context, arg CreateRiderEarningParams) (RiderEarning, error)
	CreateRiderPenalty(ctx context.Context, arg CreateRiderPenaltyParams) (RiderPenalty, error)
	CreateSearchLog(ctx context.Context, arg CreateSearchLogParams) (SearchLog, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTimelineEvent(ctx context.Context, arg CreateTimelineEventParams) (OrderTimelineEvent, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (PaymentTransaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error)
	CreditUserWallet(ctx context.Context, arg CreditUserWalletParams) error
	DeactivateProductDiscount(ctx context.Context, productID uuid.UUID) error
	DebitUserWallet(ctx context.Context, arg DebitUserWalletParams) error
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteBanner(ctx context.Context, arg DeleteBannerParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteHub(ctx context.Context, arg DeleteHubParams) error
	DeleteHubArea(ctx context.Context, id uuid.UUID) error
	DeleteModifierGroup(ctx context.Context, id uuid.UUID) error
	DeleteModifierOption(ctx context.Context, id uuid.UUID) error
	DeleteModifierOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) error
	DeleteOperatingHours(ctx context.Context, restaurantID uuid.UUID) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteRestaurant(ctx context.Context, arg DeleteRestaurantParams) error
	DeleteRider(ctx context.Context, arg DeleteRiderParams) error
	DeleteStory(ctx context.Context, arg DeleteStoryParams) error
	ExpireDiscounts(ctx context.Context) error
	FinalizeInvoice(ctx context.Context, arg FinalizeInvoiceParams) (Invoice, error)
	GetActiveAttendance(ctx context.Context, riderID uuid.UUID) (RiderAttendance, error)
	GetActiveDiscount(ctx context.Context, productID uuid.UUID) (ProductDiscount, error)
	GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (UserAddress, error)
	GetAdminOrderVolume(ctx context.Context, arg GetAdminOrderVolumeParams) ([]GetAdminOrderVolumeRow, error)
	GetAdminOverview(ctx context.Context, arg GetAdminOverviewParams) (GetAdminOverviewRow, error)
	GetAdminRevenueByPeriod(ctx context.Context, arg GetAdminRevenueByPeriodParams) ([]GetAdminRevenueByPeriodRow, error)
	GetBannerByID(ctx context.Context, arg GetBannerByIDParams) (Banner, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetDashboardToday(ctx context.Context, tenantID uuid.UUID) (GetDashboardTodayRow, error)
	GetDashboardTrend(ctx context.Context, arg GetDashboardTrendParams) ([]GetDashboardTrendRow, error)
	GetDeliveryZoneConfig(ctx context.Context, tenantID uuid.UUID) (DeliveryZoneConfig, error)
	GetFinanceSummary(ctx context.Context, tenantID uuid.UUID) (GetFinanceSummaryRow, error)
	GetHubAreaByID(ctx context.Context, id uuid.UUID) (HubCoverageArea, error)
	GetHubAreaByName(ctx context.Context, arg GetHubAreaByNameParams) (HubCoverageArea, error)
	GetHubByID(ctx context.Context, arg GetHubByIDParams) (Hub, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetInvoiceByID(ctx context.Context, arg GetInvoiceByIDParams) (Invoice, error)
	GetInvoiceByPeriod(ctx context.Context, arg GetInvoiceByPeriodParams) (Invoice, error)
	GetLastLedgerEntryBalance(ctx context.Context, accountID uuid.UUID) (pgtype.Numeric, error)
	GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpVerification, error)
	GetLedgerAccountByCode(ctx context.Context, code string) (LedgerAccount, error)
	GetModifierGroupByID(ctx context.Context, id uuid.UUID) (ProductModifierGroup, error)
	GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) (NotificationPreference, error)
	GetOrderAnalyticsByOrderID(ctx context.Context, arg GetOrderAnalyticsByOrderIDParams) (OrderAnalytic, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (Order, error)
	GetOrderForReconciliation(ctx context.Context, arg GetOrderForReconciliationParams) ([]Order, error)
	GetOrderIssueByID(ctx context.Context, arg GetOrderIssueByIDParams) (OrderIssue, error)
	GetOrderPickupsByRestaurantAndPeriod(ctx context.Context, arg GetOrderPickupsByRestaurantAndPeriodParams) ([]OrderPickup, error)
	GetOrderStatusBreakdown(ctx context.Context, arg GetOrderStatusBreakdownParams) ([]GetOrderStatusBreakdownRow, error)
	GetPeakHours(ctx context.Context, arg GetPeakHoursParams) ([]GetPeakHoursRow, error)
	GetPenaltyByID(ctx context.Context, arg GetPenaltyByIDParams) (RiderPenalty, error)
	GetPendingOrderCount(ctx context.Context, tenantID uuid.UUID) (int32, error)
	GetPickupByOrderAndRestaurant(ctx context.Context, arg GetPickupByOrderAndRestaurantParams) (OrderPickup, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductByIDPublic(ctx context.Context, id uuid.UUID) (Product, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefundByID(ctx context.Context, arg GetRefundByIDParams) (Refund, error)
	GetRestaurantAvgRating(ctx context.Context, restaurantID uuid.UUID) (GetRestaurantAvgRatingRow, error)
	GetRestaurantByID(ctx context.Context, arg GetRestaurantByIDParams) (Restaurant, error)
	GetRestaurantBySlug(ctx context.Context, arg GetRestaurantBySlugParams) (Restaurant, error)
	GetReviewByID(ctx context.Context, arg GetReviewByIDParams) (Review, error)
	GetReviewByOrderAndUser(ctx context.Context, arg GetReviewByOrderAndUserParams) (Review, error)
	GetRiderAnalytics(ctx context.Context, arg GetRiderAnalyticsParams) ([]GetRiderAnalyticsRow, error)
	GetRiderByID(ctx context.Context, arg GetRiderByIDParams) (Rider, error)
	GetRiderByUserID(ctx context.Context, arg GetRiderByUserIDParams) (Rider, error)
	GetRiderLocation(ctx context.Context, riderID uuid.UUID) (RiderLocation, error)
	GetSalesReport(ctx context.Context, arg GetSalesReportParams) ([]GetSalesReportRow, error)
	GetSectionByID(ctx context.Context, arg GetSectionByIDParams) (HomepageSection, error)
	GetStoryByID(ctx context.Context, arg GetStoryByIDParams) (Story, error)
	GetTenantAnalytics(ctx context.Context, arg GetTenantAnalyticsParams) (GetTenantAnalyticsRow, error)
	GetTenantByDomain(ctx context.Context, customDomain sql.NullString) (Tenant, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTopProducts(ctx context.Context, arg GetTopProductsParams) ([]GetTopProductsRow, error)
	GetTopSearchTerms(ctx context.Context, arg GetTopSearchTermsParams) ([]GetTopSearchTermsRow, error)
	GetTotalEarningsByRider(ctx context.Context, riderID uuid.UUID) (pgtype.Numeric, error)
	GetTransactionByGatewayID(ctx context.Context, arg GetTransactionByGatewayIDParams) (PaymentTransaction, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (PaymentTransaction, error)
	GetTransactionByOrderID(ctx context.Context, arg GetTransactionByOrderIDParams) (PaymentTransaction, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, arg GetUserByPhoneParams) (User, error)
	GetUserDevicePushToken(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	GetUserWalletBalance(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpVerification, error)
	ListActiveBanners(ctx context.Context, tenantID uuid.UUID) ([]Banner, error)
	ListActiveOrdersByRider(ctx context.Context, arg ListActiveOrdersByRiderParams) ([]Order, error)
	ListActiveRestaurantsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListActiveRestaurantsByTenantRow, error)
	ListActiveSections(ctx context.Context, tenantID uuid.UUID) ([]HomepageSection, error)
	ListActiveStories(ctx context.Context, tenantID uuid.UUID) ([]Story, error)
	ListAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error)
	ListAttendanceByRider(ctx context.Context, arg ListAttendanceByRiderParams) ([]RiderAttendance, error)
	ListAttendanceByTenant(ctx context.Context, arg ListAttendanceByTenantParams) ([]RiderAttendance, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAvailableByHubAndArea(ctx context.Context, arg ListAvailableByHubAndAreaParams) ([]Restaurant, error)
	ListAvailableProductsByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]Product, error)
	ListAvailableRidersByHub(ctx context.Context, arg ListAvailableRidersByHubParams) ([]Rider, error)
	ListBannersByTenant(ctx context.Context, arg ListBannersByTenantParams) ([]Banner, error)
	ListCategoriesByRestaurant(ctx context.Context, arg ListCategoriesByRestaurantParams) ([]Category, error)
	ListCreatedOrdersPastTimeout(ctx context.Context, limit int32) ([]Order, error)
	ListDeliveredOrdersByRider(ctx context.Context, arg ListDeliveredOrdersByRiderParams) ([]Order, error)
	ListEarningsByOrder(ctx context.Context, arg ListEarningsByOrderParams) ([]RiderEarning, error)
	ListEarningsByRider(ctx context.Context, arg ListEarningsByRiderParams) ([]RiderEarning, error)
	ListHubAreas(ctx context.Context, hubID uuid.UUID) ([]HubCoverageArea, error)
	ListHubsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Hub, error)
	ListInvoicesByRestaurant(ctx context.Context, arg ListInvoicesByRestaurantParams) ([]Invoice, error)
	ListInvoicesByTenant(ctx context.Context, arg ListInvoicesByTenantParams) ([]Invoice, error)
	ListLedgerAccounts(ctx context.Context) ([]LedgerAccount, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error)
	ListLedgerEntriesByReference(ctx context.Context, arg ListLedgerEntriesByReferenceParams) ([]LedgerEntry, error)
	ListLocationHistoryByRider(ctx context.Context, arg ListLocationHistoryByRiderParams) ([]RiderLocationHistory, error)
	ListModifierGroupsByProduct(ctx context.Context, productID uuid.UUID) ([]ProductModifierGroup, error)
	ListModifierOptionsByGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]ProductModifierOption, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListOperatingHours(ctx context.Context, restaurantID uuid.UUID) ([]RestaurantOperatingHour, error)
	ListOrderIssueMessages(ctx context.Context, arg ListOrderIssueMessagesParams) ([]OrderIssueMessage, error)
	ListOrderIssuesByOrder(ctx context.Context, arg ListOrderIssuesByOrderParams) ([]OrderIssue, error)
	ListOrderIssuesByTenant(ctx context.Context, arg ListOrderIssuesByTenantParams) ([]OrderIssue, error)
	ListOrderItemsByOrderIDs(ctx context.Context, arg ListOrderItemsByOrderIDsParams) ([]OrderItem, error)
	ListOrderItemsByRestaurantAndPeriod(ctx context.Context, arg ListOrderItemsByRestaurantAndPeriodParams) ([]OrderItem, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	ListPenaltiesByRider(ctx context.Context, arg ListPenaltiesByRiderParams) ([]RiderPenalty, error)
	ListPendingOrdersPastTimeout(ctx context.Context, arg ListPendingOrdersPastTimeoutParams) ([]Order, error)
	ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	ListPendingPaymentOrders(ctx context.Context, arg ListPendingPaymentOrdersParams) ([]Order, error)
	ListPendingTransactions(ctx context.Context, arg ListPendingTransactionsParams) ([]PaymentTransaction, error)
	ListPickupsByOrder(ctx context.Context, arg ListPickupsByOrderParams) ([]OrderPickup, error)
	ListProductsByRestaurant(ctx context.Context, arg ListProductsByRestaurantParams) ([]Product, error)
	ListRefundsByOrder(ctx context.Context, arg ListRefundsByOrderParams) ([]Refund, error)
	ListRestaurantsByTenant(ctx context.Context, arg ListRestaurantsByTenantParams) ([]Restaurant, error)
	ListReviewsByRestaurant(ctx context.Context, arg ListReviewsByRestaurantParams) ([]Review, error)
	ListRiderLocationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]RiderLocation, error)
	ListRidersByHub(ctx context.Context, arg ListRidersByHubParams) ([]Rider, error)
	ListRidersByTenant(ctx context.Context, arg ListRidersByTenantParams) ([]Rider, error)
	ListSectionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]HomepageSection, error)
	ListStoriesByTenant(ctx context.Context, arg ListStoriesByTenantParams) ([]Story, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListTimelineByOrder(ctx context.Context, arg ListTimelineByOrderParams) ([]OrderTimelineEvent, error)
	ListTransactionsByOrder(ctx context.Context, arg ListTransactionsByOrderParams) ([]PaymentTransaction, error)
	ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error)
	MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (Invoice, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	MarkOTPVerified(ctx context.Context, id uuid.UUID) error
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	// placeholder query to validate SQLC pipeline
	Ping(ctx context.Context) (int32, error)
	PublishReview(ctx context.Context, arg PublishReviewParams) (Review, error)
	PurgeOldAuditLogs(ctx context.Context, before time.Time) error
	PurgeOldNotifications(ctx context.Context, before time.Time) error
	PurgeOldOrderTimeline(ctx context.Context, before time.Time) error
	PurgeOldSearchLogs(ctx context.Context, before time.Time) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchRestaurants(ctx context.Context, arg SearchRestaurantsParams) ([]Restaurant, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error)
	UpdateAttendanceCheckout(ctx context.Context, arg UpdateAttendanceCheckoutParams) (RiderAttendance, error)
	UpdateAttendanceStats(ctx context.Context, arg UpdateAttendanceStatsParams) error
	UpdateBanner(ctx context.Context, arg UpdateBannerParams) (Banner, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error
	UpdateHub(ctx context.Context, arg UpdateHubParams) (Hub, error)
	UpdateHubArea(ctx context.Context, arg UpdateHubAreaParams) (HubCoverageArea, error)
	UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error
	UpdateModifierGroup(ctx context.Context, arg UpdateModifierGroupParams) (ProductModifierGroup, error)
	UpdateModifierOption(ctx context.Context, arg UpdateModifierOptionParams) (ProductModifierOption, error)
	UpdateOrderIssueRefund(ctx context.Context, arg UpdateOrderIssueRefundParams) (OrderIssue, error)
	UpdateOrderIssueStatus(ctx context.Context, arg UpdateOrderIssueStatusParams) (OrderIssue, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePenaltyStatus(ctx context.Context, arg UpdatePenaltyStatusParams) (RiderPenalty, error)
	UpdatePickupStatus(ctx context.Context, arg UpdatePickupStatusParams) (OrderPickup, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductAvailability(ctx context.Context, arg UpdateProductAvailabilityParams) (Product, error)
	UpdateProductHasModifiers(ctx context.Context, arg UpdateProductHasModifiersParams) error
	UpdateRefundStatus(ctx context.Context, arg UpdateRefundStatusParams) (Refund, error)
	UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) (Restaurant, error)
	UpdateRestaurantAvailability(ctx context.Context, arg UpdateRestaurantAvailabilityParams) (Restaurant, error)
	UpdateRestaurantRating(ctx context.Context, arg UpdateRestaurantRatingParams) error
	UpdateRestaurantReply(ctx context.Context, arg UpdateRestaurantReplyParams) (Review, error)
	UpdateRider(ctx context.Context, arg UpdateRiderParams) (Rider, error)
	UpdateRiderAvailability(ctx context.Context, arg UpdateRiderAvailabilityParams) (Rider, error)
	UpdateRiderDutyStatus(ctx context.Context, arg UpdateRiderDutyStatusParams) (Rider, error)
	UpdateRiderStats(ctx context.Context, arg UpdateRiderStatsParams) error
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (HomepageSection, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (PaymentTransaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertDeliveryZoneConfig(ctx context.Context, arg UpsertDeliveryZoneConfigParams) (DeliveryZoneConfig, error)
	UpsertOperatingHour(ctx context.Context, arg UpsertOperatingHourParams) (RestaurantOperatingHour, error)
	UpsertProductDiscount(ctx context.Context, arg UpsertProductDiscountParams) (ProductDiscount, error)
	UpsertRiderLocation(ctx context.Context, arg UpsertRiderLocationParams) (RiderLocation, error)
}

var _ Querier = (*Queries)(nil)
