// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rider_attendance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO rider_attendance (rider_id, tenant_id, work_date, checked_in_at)
VALUES ($1, $2, $3, $4)
RETURNING id, rider_id, tenant_id, work_date, checked_in_at, checked_out_at, total_hours, total_distance_km, completed_orders, cancelled_orders, earnings, created_at, updated_at
`

type CreateAttendanceParams struct {
	RiderID     uuid.UUID          `json:"rider_id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	WorkDate    pgtype.Date        `json:"work_date"`
	CheckedInAt pgtype.Timestamptz `json:"checked_in_at"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (RiderAttendance, error) {
	row := q.db.QueryRow(ctx, createAttendance,
		arg.RiderID,
		arg.TenantID,
		arg.WorkDate,
		arg.CheckedInAt,
	)
	var i RiderAttendance
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.TenantID,
		&i.WorkDate,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.TotalHours,
		&i.TotalDistanceKm,
		&i.CompletedOrders,
		&i.CancelledOrders,
		&i.Earnings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAttendance = `-- name: GetActiveAttendance :one
SELECT id, rider_id, tenant_id, work_date, checked_in_at, checked_out_at, total_hours, total_distance_km, completed_orders, cancelled_orders, earnings, created_at, updated_at FROM rider_attendance
WHERE rider_id = $1 AND checked_out_at IS NULL
ORDER BY checked_in_at DESC
LIMIT 1
`

func (q *Queries) GetActiveAttendance(ctx context.Context, riderID uuid.UUID) (RiderAttendance, error) {
	row := q.db.QueryRow(ctx, getActiveAttendance, riderID)
	var i RiderAttendance
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.TenantID,
		&i.WorkDate,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.TotalHours,
		&i.TotalDistanceKm,
		&i.CompletedOrders,
		&i.CancelledOrders,
		&i.Earnings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttendanceByRider = `-- name: ListAttendanceByRider :many
SELECT id, rider_id, tenant_id, work_date, checked_in_at, checked_out_at, total_hours, total_distance_km, completed_orders, cancelled_orders, earnings, created_at, updated_at FROM rider_attendance
WHERE rider_id = $1
ORDER BY work_date DESC
LIMIT $2 OFFSET $3
`

type ListAttendanceByRiderParams struct {
	RiderID uuid.UUID `json:"rider_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListAttendanceByRider(ctx context.Context, arg ListAttendanceByRiderParams) ([]RiderAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendanceByRider, arg.RiderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiderAttendance{}
	for rows.Next() {
		var i RiderAttendance
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.TenantID,
			&i.WorkDate,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.TotalHours,
			&i.TotalDistanceKm,
			&i.CompletedOrders,
			&i.CancelledOrders,
			&i.Earnings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceByTenant = `-- name: ListAttendanceByTenant :many
SELECT id, rider_id, tenant_id, work_date, checked_in_at, checked_out_at, total_hours, total_distance_km, completed_orders, cancelled_orders, earnings, created_at, updated_at FROM rider_attendance
WHERE tenant_id = $1 AND work_date = $4::date
ORDER BY checked_in_at DESC
LIMIT $2 OFFSET $3
`

type ListAttendanceByTenantParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	WorkDate pgtype.Date `json:"work_date"`
}

func (q *Queries) ListAttendanceByTenant(ctx context.Context, arg ListAttendanceByTenantParams) ([]RiderAttendance, error) {
	rows, err := q.db.Query(ctx, listAttendanceByTenant,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.WorkDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiderAttendance{}
	for rows.Next() {
		var i RiderAttendance
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.TenantID,
			&i.WorkDate,
			&i.CheckedInAt,
			&i.CheckedOutAt,
			&i.TotalHours,
			&i.TotalDistanceKm,
			&i.CompletedOrders,
			&i.CancelledOrders,
			&i.Earnings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendanceCheckout = `-- name: UpdateAttendanceCheckout :one
UPDATE rider_attendance SET
  checked_out_at = $2,
  total_hours = $3,
  total_distance_km = $4
WHERE id = $1
RETURNING id, rider_id, tenant_id, work_date, checked_in_at, checked_out_at, total_hours, total_distance_km, completed_orders, cancelled_orders, earnings, created_at, updated_at
`

type UpdateAttendanceCheckoutParams struct {
	ID              uuid.UUID          `json:"id"`
	CheckedOutAt    pgtype.Timestamptz `json:"checked_out_at"`
	TotalHours      pgtype.Numeric     `json:"total_hours"`
	TotalDistanceKm pgtype.Numeric     `json:"total_distance_km"`
}

func (q *Queries) UpdateAttendanceCheckout(ctx context.Context, arg UpdateAttendanceCheckoutParams) (RiderAttendance, error) {
	row := q.db.QueryRow(ctx, updateAttendanceCheckout,
		arg.ID,
		arg.CheckedOutAt,
		arg.TotalHours,
		arg.TotalDistanceKm,
	)
	var i RiderAttendance
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.TenantID,
		&i.WorkDate,
		&i.CheckedInAt,
		&i.CheckedOutAt,
		&i.TotalHours,
		&i.TotalDistanceKm,
		&i.CompletedOrders,
		&i.CancelledOrders,
		&i.Earnings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAttendanceStats = `-- name: UpdateAttendanceStats :exec
UPDATE rider_attendance SET
  completed_orders = completed_orders + 1,
  earnings = earnings + $2
WHERE id = $1
`

type UpdateAttendanceStatsParams struct {
	ID       uuid.UUID      `json:"id"`
	Earnings pgtype.Numeric `json:"earnings"`
}

func (q *Queries) UpdateAttendanceStats(ctx context.Context, arg UpdateAttendanceStatsParams) error {
	_, err := q.db.Exec(ctx, updateAttendanceStats, arg.ID, arg.Earnings)
	return err
}
