// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: riders.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRidersByTenant = `-- name: CountRidersByTenant :one
SELECT COUNT(*) FROM riders WHERE tenant_id = $1
`

func (q *Queries) CountRidersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRidersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRider = `-- name: CreateRider :one
INSERT INTO riders (tenant_id, user_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at
`

type CreateRiderParams struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	UserID              uuid.UUID      `json:"user_id"`
	HubID               pgtype.UUID    `json:"hub_id"`
	VehicleType         VehicleType    `json:"vehicle_type"`
	VehicleRegistration sql.NullString `json:"vehicle_registration"`
	LicenseNumber       sql.NullString `json:"license_number"`
	NidNumber           sql.NullString `json:"nid_number"`
	NidVerified         bool           `json:"nid_verified"`
}

func (q *Queries) CreateRider(ctx context.Context, arg CreateRiderParams) (Rider, error) {
	row := q.db.QueryRow(ctx, createRider,
		arg.TenantID,
		arg.UserID,
		arg.HubID,
		arg.VehicleType,
		arg.VehicleRegistration,
		arg.LicenseNumber,
		arg.NidNumber,
		arg.NidVerified,
	)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRider = `-- name: DeleteRider :exec
DELETE FROM riders WHERE id = $1 AND tenant_id = $2
`

type DeleteRiderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRider(ctx context.Context, arg DeleteRiderParams) error {
	_, err := q.db.Exec(ctx, deleteRider, arg.ID, arg.TenantID)
	return err
}

const getRiderByID = `-- name: GetRiderByID :one
SELECT id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at FROM riders WHERE id = $1 AND tenant_id = $2 LIMIT 1
`

type GetRiderByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRiderByID(ctx context.Context, arg GetRiderByIDParams) (Rider, error) {
	row := q.db.QueryRow(ctx, getRiderByID, arg.ID, arg.TenantID)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRiderByUserID = `-- name: GetRiderByUserID :one
SELECT id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at FROM riders WHERE user_id = $1 AND tenant_id = $2 LIMIT 1
`

type GetRiderByUserIDParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRiderByUserID(ctx context.Context, arg GetRiderByUserIDParams) (Rider, error) {
	row := q.db.QueryRow(ctx, getRiderByUserID, arg.UserID, arg.TenantID)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAvailableRidersByHub = `-- name: ListAvailableRidersByHub :many
SELECT id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at FROM riders WHERE hub_id = $1 AND tenant_id = $2 AND is_available = true AND is_on_duty = true
`

type ListAvailableRidersByHubParams struct {
	HubID    pgtype.UUID `json:"hub_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) ListAvailableRidersByHub(ctx context.Context, arg ListAvailableRidersByHubParams) ([]Rider, error) {
	rows, err := q.db.Query(ctx, listAvailableRidersByHub, arg.HubID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rider{}
	for rows.Next() {
		var i Rider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.HubID,
			&i.VehicleType,
			&i.VehicleRegistration,
			&i.LicenseNumber,
			&i.NidNumber,
			&i.NidVerified,
			&i.IsAvailable,
			&i.IsOnDuty,
			&i.TotalOrderCount,
			&i.TotalEarnings,
			&i.PendingBalance,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidersByHub = `-- name: ListRidersByHub :many
SELECT id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at FROM riders WHERE hub_id = $1 AND tenant_id = $2 ORDER BY created_at DESC
`

type ListRidersByHubParams struct {
	HubID    pgtype.UUID `json:"hub_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) ListRidersByHub(ctx context.Context, arg ListRidersByHubParams) ([]Rider, error) {
	rows, err := q.db.Query(ctx, listRidersByHub, arg.HubID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rider{}
	for rows.Next() {
		var i Rider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.HubID,
			&i.VehicleType,
			&i.VehicleRegistration,
			&i.LicenseNumber,
			&i.NidNumber,
			&i.NidVerified,
			&i.IsAvailable,
			&i.IsOnDuty,
			&i.TotalOrderCount,
			&i.TotalEarnings,
			&i.PendingBalance,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRidersByTenant = `-- name: ListRidersByTenant :many
SELECT id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at FROM riders WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRidersByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListRidersByTenant(ctx context.Context, arg ListRidersByTenantParams) ([]Rider, error) {
	rows, err := q.db.Query(ctx, listRidersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rider{}
	for rows.Next() {
		var i Rider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.HubID,
			&i.VehicleType,
			&i.VehicleRegistration,
			&i.LicenseNumber,
			&i.NidNumber,
			&i.NidVerified,
			&i.IsAvailable,
			&i.IsOnDuty,
			&i.TotalOrderCount,
			&i.TotalEarnings,
			&i.PendingBalance,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRider = `-- name: UpdateRider :one
UPDATE riders SET
  hub_id = COALESCE($1, hub_id),
  vehicle_type = COALESCE($2, vehicle_type),
  vehicle_registration = COALESCE($3, vehicle_registration),
  license_number = COALESCE($4, license_number),
  nid_number = COALESCE($5, nid_number),
  nid_verified = COALESCE($6, nid_verified),
  rating_avg = COALESCE($7, rating_avg),
  rating_count = COALESCE($8, rating_count)
WHERE id = $9 AND tenant_id = $10
RETURNING id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at
`

type UpdateRiderParams struct {
	HubID               pgtype.UUID     `json:"hub_id"`
	VehicleType         NullVehicleType `json:"vehicle_type"`
	VehicleRegistration sql.NullString  `json:"vehicle_registration"`
	LicenseNumber       sql.NullString  `json:"license_number"`
	NidNumber           sql.NullString  `json:"nid_number"`
	NidVerified         *bool           `json:"nid_verified"`
	RatingAvg           pgtype.Numeric  `json:"rating_avg"`
	RatingCount         *int32          `json:"rating_count"`
	ID                  uuid.UUID       `json:"id"`
	TenantID            uuid.UUID       `json:"tenant_id"`
}

func (q *Queries) UpdateRider(ctx context.Context, arg UpdateRiderParams) (Rider, error) {
	row := q.db.QueryRow(ctx, updateRider,
		arg.HubID,
		arg.VehicleType,
		arg.VehicleRegistration,
		arg.LicenseNumber,
		arg.NidNumber,
		arg.NidVerified,
		arg.RatingAvg,
		arg.RatingCount,
		arg.ID,
		arg.TenantID,
	)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRiderAvailability = `-- name: UpdateRiderAvailability :one
UPDATE riders SET is_available = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at
`

type UpdateRiderAvailabilityParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	IsAvailable bool      `json:"is_available"`
}

func (q *Queries) UpdateRiderAvailability(ctx context.Context, arg UpdateRiderAvailabilityParams) (Rider, error) {
	row := q.db.QueryRow(ctx, updateRiderAvailability, arg.ID, arg.TenantID, arg.IsAvailable)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRiderDutyStatus = `-- name: UpdateRiderDutyStatus :one
UPDATE riders SET is_on_duty = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, user_id, tenant_id, hub_id, vehicle_type, vehicle_registration, license_number, nid_number, nid_verified, is_available, is_on_duty, total_order_count, total_earnings, pending_balance, rating_avg, rating_count, created_at, updated_at
`

type UpdateRiderDutyStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	IsOnDuty bool      `json:"is_on_duty"`
}

func (q *Queries) UpdateRiderDutyStatus(ctx context.Context, arg UpdateRiderDutyStatusParams) (Rider, error) {
	row := q.db.QueryRow(ctx, updateRiderDutyStatus, arg.ID, arg.TenantID, arg.IsOnDuty)
	var i Rider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.HubID,
		&i.VehicleType,
		&i.VehicleRegistration,
		&i.LicenseNumber,
		&i.NidNumber,
		&i.NidVerified,
		&i.IsAvailable,
		&i.IsOnDuty,
		&i.TotalOrderCount,
		&i.TotalEarnings,
		&i.PendingBalance,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRiderStats = `-- name: UpdateRiderStats :exec
UPDATE riders SET
  total_order_count = total_order_count + 1,
  total_earnings = total_earnings + $3,
  pending_balance = pending_balance + $4
WHERE id = $1 AND tenant_id = $2
`

type UpdateRiderStatsParams struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	TotalEarnings  pgtype.Numeric `json:"total_earnings"`
	PendingBalance pgtype.Numeric `json:"pending_balance"`
}

func (q *Queries) UpdateRiderStats(ctx context.Context, arg UpdateRiderStatsParams) error {
	_, err := q.db.Exec(ctx, updateRiderStats,
		arg.ID,
		arg.TenantID,
		arg.TotalEarnings,
		arg.PendingBalance,
	)
	return err
}
