// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, name, status, plan, commission_rate, settings, contact_email, contact_phone, address, timezone, currency, locale, logo_url, favicon_url, primary_color, secondary_color, custom_domain)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at
`

type CreateTenantParams struct {
	Slug           string          `json:"slug"`
	Name           string          `json:"name"`
	Status         TenantStatus    `json:"status"`
	Plan           TenantPlan      `json:"plan"`
	CommissionRate pgtype.Numeric  `json:"commission_rate"`
	Settings       json.RawMessage `json:"settings"`
	ContactEmail   string          `json:"contact_email"`
	ContactPhone   sql.NullString  `json:"contact_phone"`
	Address        []byte          `json:"address"`
	Timezone       string          `json:"timezone"`
	Currency       string          `json:"currency"`
	Locale         string          `json:"locale"`
	LogoUrl        sql.NullString  `json:"logo_url"`
	FaviconUrl     sql.NullString  `json:"favicon_url"`
	PrimaryColor   string          `json:"primary_color"`
	SecondaryColor string          `json:"secondary_color"`
	CustomDomain   sql.NullString  `json:"custom_domain"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Slug,
		arg.Name,
		arg.Status,
		arg.Plan,
		arg.CommissionRate,
		arg.Settings,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Address,
		arg.Timezone,
		arg.Currency,
		arg.Locale,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.CustomDomain,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at FROM tenants WHERE custom_domain = $1 LIMIT 1
`

func (q *Queries) GetTenantByDomain(ctx context.Context, customDomain sql.NullString) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByDomain, customDomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at FROM tenants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at FROM tenants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at FROM tenants ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Plan,
			&i.SubscriptionPlanID,
			&i.CommissionRate,
			&i.Settings,
			&i.CustomDomain,
			&i.LogoUrl,
			&i.FaviconUrl,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.Address,
			&i.Timezone,
			&i.Currency,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET
  name = COALESCE($1, name),
  logo_url = COALESCE($2, logo_url),
  favicon_url = COALESCE($3, favicon_url),
  primary_color = COALESCE($4, primary_color),
  secondary_color = COALESCE($5, secondary_color),
  contact_email = COALESCE($6, contact_email),
  contact_phone = COALESCE($7, contact_phone),
  settings = COALESCE($8, settings),
  custom_domain = COALESCE($9, custom_domain),
  address = COALESCE($10, address),
  timezone = COALESCE($11, timezone),
  currency = COALESCE($12, currency),
  locale = COALESCE($13, locale)
WHERE id = $14
RETURNING id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at
`

type UpdateTenantParams struct {
	Name           sql.NullString `json:"name"`
	LogoUrl        sql.NullString `json:"logo_url"`
	FaviconUrl     sql.NullString `json:"favicon_url"`
	PrimaryColor   sql.NullString `json:"primary_color"`
	SecondaryColor sql.NullString `json:"secondary_color"`
	ContactEmail   sql.NullString `json:"contact_email"`
	ContactPhone   sql.NullString `json:"contact_phone"`
	Settings       []byte         `json:"settings"`
	CustomDomain   sql.NullString `json:"custom_domain"`
	Address        []byte         `json:"address"`
	Timezone       sql.NullString `json:"timezone"`
	Currency       sql.NullString `json:"currency"`
	Locale         sql.NullString `json:"locale"`
	ID             uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.Name,
		arg.LogoUrl,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Settings,
		arg.CustomDomain,
		arg.Address,
		arg.Timezone,
		arg.Currency,
		arg.Locale,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants SET status = $2 WHERE id = $1 RETURNING id, slug, name, status, plan, subscription_plan_id, commission_rate, settings, custom_domain, logo_url, favicon_url, primary_color, secondary_color, contact_email, contact_phone, address, timezone, currency, locale, created_at, updated_at
`

type UpdateTenantStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status TenantStatus `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Plan,
		&i.SubscriptionPlanID,
		&i.CommissionRate,
		&i.Settings,
		&i.CustomDomain,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.Address,
		&i.Timezone,
		&i.Currency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
