// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_addresses.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultAddresses = `-- name: ClearDefaultAddresses :exec
UPDATE user_addresses SET is_default = false WHERE user_id = $1
`

func (q *Queries) ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddresses, userID)
	return err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO user_addresses (user_id, tenant_id, label, recipient_name, recipient_phone, address_line1, address_line2, area, city, geo_lat, geo_lng, geo_display_addr, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, tenant_id, label, recipient_name, recipient_phone, address_line1, address_line2, area, city, geo_lat, geo_lng, geo_display_addr, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	Label          string         `json:"label"`
	RecipientName  sql.NullString `json:"recipient_name"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
	AddressLine1   string         `json:"address_line1"`
	AddressLine2   sql.NullString `json:"address_line2"`
	Area           string         `json:"area"`
	City           string         `json:"city"`
	GeoLat         pgtype.Numeric `json:"geo_lat"`
	GeoLng         pgtype.Numeric `json:"geo_lng"`
	GeoDisplayAddr sql.NullString `json:"geo_display_addr"`
	IsDefault      bool           `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.TenantID,
		arg.Label,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Area,
		arg.City,
		arg.GeoLat,
		arg.GeoLng,
		arg.GeoDisplayAddr,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Label,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Area,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeoDisplayAddr,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM user_addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, tenant_id, label, recipient_name, recipient_phone, address_line1, address_line2, area, city, geo_lat, geo_lng, geo_display_addr, is_default, created_at, updated_at FROM user_addresses WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetAddressByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.ID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Label,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Area,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeoDisplayAddr,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, user_id, tenant_id, label, recipient_name, recipient_phone, address_line1, address_line2, area, city, geo_lat, geo_lng, geo_display_addr, is_default, created_at, updated_at FROM user_addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAddress{}
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Label,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.Area,
			&i.City,
			&i.GeoLat,
			&i.GeoLng,
			&i.GeoDisplayAddr,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE user_addresses SET
  label = COALESCE($1, label),
  recipient_name = COALESCE($2, recipient_name),
  recipient_phone = COALESCE($3, recipient_phone),
  address_line1 = COALESCE($4, address_line1),
  address_line2 = COALESCE($5, address_line2),
  area = COALESCE($6, area),
  city = COALESCE($7, city),
  geo_lat = COALESCE($8, geo_lat),
  geo_lng = COALESCE($9, geo_lng),
  geo_display_addr = COALESCE($10, geo_display_addr),
  is_default = COALESCE($11, is_default)
WHERE id = $12 AND user_id = $13
RETURNING id, user_id, tenant_id, label, recipient_name, recipient_phone, address_line1, address_line2, area, city, geo_lat, geo_lng, geo_display_addr, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	Label          sql.NullString `json:"label"`
	RecipientName  sql.NullString `json:"recipient_name"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
	AddressLine1   sql.NullString `json:"address_line1"`
	AddressLine2   sql.NullString `json:"address_line2"`
	Area           sql.NullString `json:"area"`
	City           sql.NullString `json:"city"`
	GeoLat         pgtype.Numeric `json:"geo_lat"`
	GeoLng         pgtype.Numeric `json:"geo_lng"`
	GeoDisplayAddr sql.NullString `json:"geo_display_addr"`
	IsDefault      *bool          `json:"is_default"`
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.Label,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Area,
		arg.City,
		arg.GeoLat,
		arg.GeoLng,
		arg.GeoDisplayAddr,
		arg.IsDefault,
		arg.ID,
		arg.UserID,
	)
	var i UserAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Label,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Area,
		&i.City,
		&i.GeoLat,
		&i.GeoLng,
		&i.GeoDisplayAddr,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
