// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_transactions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*) FROM wallet_transactions WHERE user_id = $1
`

func (q *Queries) CountWalletTransactions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (
    user_id, tenant_id, order_id, type, source, amount, balance_after, description, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, tenant_id, order_id, type, source, amount, balance_after, description, expires_at, created_at
`

type CreateWalletTransactionParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	OrderID      pgtype.UUID        `json:"order_id"`
	Type         WalletType         `json:"type"`
	Source       WalletSource       `json:"source"`
	Amount       pgtype.Numeric     `json:"amount"`
	BalanceAfter pgtype.Numeric     `json:"balance_after"`
	Description  sql.NullString     `json:"description"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.UserID,
		arg.TenantID,
		arg.OrderID,
		arg.Type,
		arg.Source,
		arg.Amount,
		arg.BalanceAfter,
		arg.Description,
		arg.ExpiresAt,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.OrderID,
		&i.Type,
		&i.Source,
		&i.Amount,
		&i.BalanceAfter,
		&i.Description,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const creditUserWallet = `-- name: CreditUserWallet :exec
UPDATE users SET wallet_balance = wallet_balance + $2 WHERE id = $1 AND deleted_at IS NULL
`

type CreditUserWalletParams struct {
	ID     uuid.UUID      `json:"id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreditUserWallet(ctx context.Context, arg CreditUserWalletParams) error {
	_, err := q.db.Exec(ctx, creditUserWallet, arg.ID, arg.Amount)
	return err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, user_id, tenant_id, order_id, type, source, amount, balance_after, description, expires_at, created_at FROM wallet_transactions WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.OrderID,
			&i.Type,
			&i.Source,
			&i.Amount,
			&i.BalanceAfter,
			&i.Description,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
