// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*) FROM wallet_transactions WHERE user_id = $1
`

func (q *Queries) CountWalletTransactions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, user_id, tenant_id, order_id, type, source, amount, balance_after, description, expires_at, created_at FROM wallet_transactions WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.OrderID,
			&i.Type,
			&i.Source,
			&i.Amount,
			&i.BalanceAfter,
			&i.Description,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
